# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

pool:
  vmImage: ubuntu-latest

variables:
  -group : aks

stages:
  - stage: tfVallidate
    jobs:
      - job: vaidate
        continueOnError: false
        steps:
          #terraform install
          - task: TerraformInstaller@1
            displayName: tfinstall
            inputs:
              terraformVersion: 'latest'
          
          #terraform init
          - task: TerraformTaskV4@4
            inputs:
              provider: 'azurerm'
              command: 'init'
              backendServiceArm: 'aks connection'
              backendAzureRmResourceGroupName: 'mtc-rg'
              backendAzureRmStorageAccountName: 'mtstr32444'
              backendAzureRmContainerName: 'tfstate'
              backendAzureRmKey: 'devpipeline.terraform.tfstate'
          
          #Terraform validate
          - task: TerraformTaskV4@4
            displayName: Terrafrom Validate
            inputs:
              provider: 'azurerm'
              command: 'validate'

  - stage: tfDeploy
    condition: succeeded('tfVallidate')
    dependsOn: tfVallidate
    
    jobs:
      - job: Apply
        steps: 
        #Terraform install
        - task: TerraformInstaller@1
          displayName: tfinstall
          inputs:
            terraformVersion: 'latest'
      
        #Terraform init
        - task: TerraformTaskV4@4
          inputs:
            provider: 'azurerm'
            command: 'init'
            backendServiceArm: 'aks connection'
            backendAzureRmResourceGroupName: 'mtc-rg'
            backendAzureRmStorageAccountName: 'mtstr32444'
            backendAzureRmContainerName: 'tfstate'
            backendAzureRmKey: 'devpipeline.terraform.tfstate'
        
        #Terraform plan
        - task: TerraformTaskV4@4
          inputs:
            provider: 'azurerm'
            command: 'plan'
            environmentServiceNameAzureRM: 'Azure for Students(d8026e85-c3a9-4a33-acb5-88d88c4daf6c)'
        
        #Terraform Apply
        - task: TerraformTaskV4@4
          inputs:
            provider: 'azurerm'
            command: 'apply'
            environmentServiceNameAzureRM: 'Azure for Students(d8026e85-c3a9-4a33-acb5-88d88c4daf6c)'


